// @flow
import hotel from '../fakeHotel';
import Header from './Header';
import withFakeData from '../withFakeData';

import type { PicturesArray } from '../fakeHotel';
import type { Image } from '../../gallery/GalleryGrid';

// This will be replaced with type generated by Relay compiler
export type HeaderContainer_hotel = {
  name: string,
  stars: 1 | 2 | 3 | 4 | 5,
  rating: {
    score: number,
    description: string,
  },
  photoUrl: string,
  pictures: PicturesArray,
};

type ContainerProps = {
  openGallery: (hotelName: string, images: Image[]) => void,
};

export default withFakeData(Header, (containerProps: ContainerProps) => ({
  ...containerProps,
  hotel,
}));
