// @flow

/* eslint-disable monorepo/no-relative-import */
import '../../../app/hotels/src/singleHotel/roomPicker/__tests__/RoomPicker.test.js';
import '../../../app/hotels/src/singleHotel/roomList/__tests__/RoomImage.test.js';
import '../../../app/hotels/src/singleHotel/roomList/__tests__/RoomBadges.test.js';
import '../../../app/hotels/src/singleHotel/brandLabel/__tests__/BrandLabel.test.js';
import '../../../app/hotels/src/gallery/__tests__/PhotosStripeHeader.test.js';
import '../../../app/hotels/src/filter/stars/__tests__/StarsPopup.test.js';
import '../../../app/hotels/src/filter/stars/__tests__/StarsFilter.test.js';
import '../../../app/hotels/src/components/__tests__/HotelReviewScore.playground.test.js';
import '../../../app/hotels/src/allHotels/__tests__/LoadMoreButton.test.js';
import '../../shared/src/popup/__tests__/ButtonPopupPlayground.test.js';
import '../../shared/src/loaders/__tests__/FullPageLoading.test.js';
import '../../shared/src/forms/datePicker/__tests__/DatePicker.test.js';
import '../../shared/src/forms/__tests__/TextInput.test.js';
import '../../shared/src/forms/__tests__/Switch.test.js';
import '../../shared/src/forms/__tests__/Slider.test.js';
import '../../shared/src/forms/__tests__/Checkbox.test.js';
import '../../shared/src/forms/__tests__/AgePicker.test.js';
import '../../shared/src/buttons/__tests__/TextButton.test.js';
import '../../shared/src/buttons/__tests__/LinkButton.test.js';
import '../../shared/src/buttons/__tests__/IncrementDecrementButtons.playground.test.js';
import '../../shared/src/buttons/__tests__/Button.test.js';
import '../../shared/src/__tests__/Text.test.js';
import '../../shared/src/__tests__/SimpleCard.test.js';
import '../../shared/src/readMore/__tests__/ReadMore.test.js';
import '../../shared/src/__tests__/DropMarker.playground.test.js';
import '../../shared/src/__tests__/AdaptableBadge.test.js';
import '../../shared/src/offlineScreen/__tests__/OfflineScreen.test';
