// @flow

/* eslint-disable monorepo/no-relative-import */
import '../../../app/hotels/src/singleHotel/roomPicker/__tests__/RoomPicker.test';
import '../../../app/hotels/src/singleHotel/roomList/__tests__/RoomImage.test';
import '../../../app/hotels/src/singleHotel/roomList/__tests__/RoomBadges.test';
import '../../../app/hotels/src/singleHotel/brandLabel/__tests__/BrandLabel.test';
import '../../../app/hotels/src/gallery/__tests__/PhotosStripeHeader.test';
import '../../../app/hotels/src/filter/stars/__tests__/StarsPopup.test';
import '../../../app/hotels/src/filter/stars/__tests__/StarsFilter.test';
import '../../../app/hotels/src/components/__tests__/HotelReviewScore.playground.test';
import '../../../app/hotels/src/allHotels/__tests__/LoadMoreButton.test';
import '../../shared/src/popup/__tests__/ButtonPopupPlayground.test';
import '../../shared/src/loaders/__tests__/FullPageLoading.test';
import '../../shared/src/forms/datePicker/__tests__/DatePicker.test';
import '../../shared/src/forms/__tests__/TextInput.test';
import '../../shared/src/forms/__tests__/Switch.test';
import '../../shared/src/forms/__tests__/Slider.test';
import '../../shared/src/forms/__tests__/Checkbox.test';
import '../../shared/src/forms/__tests__/AgePicker.test';
import '../../shared/src/buttons/__tests__/TextButton.test';
import '../../shared/src/buttons/__tests__/LinkButton.test';
import '../../shared/src/buttons/__tests__/IncrementDecrementButtons.playground.test';
import '../../shared/src/buttons/__tests__/Button.test';
import '../../shared/src/__tests__/Text.test';
import '../../shared/src/__tests__/SimpleCard.test';
import '../../shared/src/readMore/__tests__/ReadMore.test';
import '../../shared/src/__tests__/DropMarker.playground.test';
import '../../shared/src/__tests__/AdaptableBadge.test';
import '../../shared/src/offlineScreen/__tests__/OfflineScreen.test';
