// @flow strict

export default {
  'hotels.gallery_grid.no_images': 'No images available.',
  'hotels.gallery.pagination': '__1_photoNumber__ of __2_totalPhotos__',
  'hotels.map.address': 'Address',
  'hotels.map.multiple_reviews': 'Total reviews: __numberOfReviews__',
  'hotels.map.no_results': 'No results. Please try using a different filter.',
  'hotels.map.no_reviews': 'No reviews',
  'hotels.navigation.title.all_hotels': 'Hotels',
  'hotels.navigation.title.all_hotels_map': 'Map',
  'hotels.navigation.title.gallery_grid': 'Photos',
  'hotels.navigation.title.payment': 'Hotel',
  'hotels.navigation.title.single_hotel': 'Details',
  'hotels.navigation.title.single_hotel_map': 'Map',

  'hotels.payment_screen.server_error':
    'Failed to get url from the server, please try again.',

  'hotels_search.all_hotels.please_search':
    'Please search for your desired destination.',
  'hotels_search.all_hotels_search_list.no_hotels_found': 'No hotels found.',
  'hotels_search.all_hotels_search.date_error':
    'Oops, there seems to be something wrong with the chosen dates',
  'hotels_search.all_hotels_map.allow_localization_or_search':
    'Please go to settings and allow localization, or go back and search for your desired destination',
  'hotels_search.date_picker.select_date': 'Select date',
  'hotels_search.filter.free_cancellation': 'free cancellation',
  'hotels_search.filter.hotel_facilities_filter.airport_shuttle':
    'Airport shuttle',
  'hotels_search.filter.hotel_facilities_filter.family_rooms': 'Family rooms',
  'hotels_search.filter.hotel_facilities_filter.facilities_for_disabled':
    'Facilities for Disabled Guests',
  'hotels_search.filter.hotel_facilities_filter.fitness_center':
    'Fitness Center',
  'hotels_search.filter.hotel_facilities_filter.parking': 'Parking',
  'hotels_search.filter.hotel_facilities_filter.free_parking': 'Free Parking',
  'hotels_search.filter.hotel_facilities_filter.valet_parking': 'Valet Parking',
  'hotels_search.filter.hotel_facilities_filter.indoor_pool': 'Indoor Pool',
  'hotels_search.filter.hotel_facilities_filter.pets_allowed': 'Pets allowed',
  'hotels_search.filter.hotel_facilities_filter.spa': 'Spa',
  'hotels_search.filter.hotel_facilities_filter.title': 'amenities',
  'hotels_search.filter.hotel_facilities_filter.wifi': 'Wi-Fi',
  'hotels_search.filter.hotel_facilities_popup.save': 'Save',
  'hotels_search.filter.hotel_facilities_popup.close': 'Close',
  'hotels_search.filter.hotel_facilities_popup.title': 'Hotel facilities',
  'hotels_search.filter.price_filter.price': 'price',
  'hotels_search.filter.price_popup.save': 'Save',
  'hotels_search.filter.price_popup.title': 'Price range',
  'hotels_search.filter.price_popup.subtitle': 'per stay',
  'hotels_search.filter.price_popup.price_label': '__1_amount__ __2_currency__',
  'hotels_search.filter.score_filter.rating': 'Rating',
  'hotels_search.filter.score_filter.rating.6': 'pleasant 6+',
  'hotels_search.filter.score_filter.rating.7': 'good 7+',
  'hotels_search.filter.score_filter.rating.8': 'very good 8+',
  'hotels_search.filter.score_filter.rating.9': 'superb 9+',
  'hotels_search.filter.score_filter.rating.any': 'any',
  'hotels_search.filter.score_popup.save': 'Save',
  'hotels_search.filter.score_popup.title': 'Rating:',
  'hotels_search.filter.stars_filter.stars': 'stars',
  'hotels_search.filter.stars_filter.unrated': 'unrated',
  'hotels_search.filter.stars_popup.save': 'Save',
  'hotels_search.filter.stars_popup.title': 'Hotel stars',
  'hotels_search.filter.stars_popup.unrated': 'Unrated',
  'hotels_search.filter.order_by': 'sort',
  'hotels_search.filter.order_filter.price': 'price',
  'hotels_search.filter.order_filter.distance': 'distance from center',
  'hotels_search.filter.order_filter.stars': 'stars',
  'hotels_search.filter.order_popup.price': 'Price',
  'hotels_search.filter.order_popup.distance': 'Distance from center',
  'hotels_search.filter.order_popup.title': 'Sort by',
  'hotels_search.filter.order_popup.stars': 'Stars',
  'hotels_search.guests.adults': 'Adults:',
  'hotels_search.guests.age_control.less_than_one': 'Less than year',
  'hotels_search.guests.age_control.select': 'Please select',
  'hotels_search.guests.children': 'Children:',
  'hotels_search.guests_number_controls.adults': 'Adults',
  'hotels_search.guests_number_controls.children': 'Children',
  'hotels_search.guests_modal.child_age_title': "Child's age at check-out",
  'hotels_search.guests_modal.children.error_age':
    "Please provide the child's age first.",
  'hotels_search.guests_modal.children_index': 'Child __index__',
  'hotels_search.guests_modal.close': 'Close',
  'hotels_search.guests_modal.header': 'Guests',
  'hotels_search.guests_modal.save': 'Save',
  'hotels_search.load_more': 'Load more...',
  'hotels_search.location_button.placeholder': 'Where?',
  'hotels_search.location_picker.cancel': 'Cancel',
  'hotels_search.location_picker.header': 'Where',
  'hotels_search.location_picker.recent_search': 'Recent search',
  'hotels_search.header.to': 'to',

  'single_hotel.bedding_info.guests': '__numberOfGuests__ Guests',
  'single_hotel.book_now': 'Book Now',
  'single_hotel.book_now.description':
    '__1_personCount__ Guests · __2_numberOfRooms__ Rooms',
  'single_hotel.description.facilities.show_less': 'Show less',
  'single_hotel.description.facilities.show_more': 'More',
  'single_hotel.hotel_detail_screen.hotel_not_found': 'Hotel not found.',
  'single_hotel.room_badges.breakfast_included': 'Breakfast included',
  'single_hotel.room_badges.free_cancellation': 'Free cancellation',
  'single_hotel.room_list.rooms': 'Rooms',
  'single_hotel.room_picker.select': 'Select',
  'single_hotel.powered_by': 'Powered by',
  'single_hotel.description.description': 'Description',
  'single_hotel.description.show_more': 'Show More',
  'single_hotel.description.show_less': 'Show Less',
  'single_hotel.room_description.read_more': 'Read more',
  'single_hotel.room_description.hide': 'Hide',
  'single_hotel.hotel_review.reviews': '__count__ Reviews',
  'single_hotel.hotel_review.rating.6': 'Pleasant',
  'single_hotel.hotel_review.rating.7': 'Good',
  'single_hotel.hotel_review.rating.8': 'Very good',
  'single_hotel.hotel_review.rating.9': 'Perfect',
  'single_hotel.room_summary.summary': 'Summary',
  'single_hotel.increment_decrement.count': 'Count',
};
