// @flow strict

const HotelsVocabulary = {
  'hotels.gallery_grid.no_images': 'No images available.',
  'hotels.gallery.pagination': '__1_photoNumber__ of __2_totalPhotos__',
  'hotels.map.address': 'Address',
  'hotels.map.no_results': 'No results. Please try using a different filter.',
  'hotels.navigation.title.gallery_grid': 'Photos',
  'hotels.navigation.title.payment': 'Hotel',

  'hotels.payment_screen.server_error':
    'Failed to get url from the server, please try again.',

  'hotels_search.all_hotels_search_list.no_hotels_found': 'No hotels found.',
  'hotels_search.all_hotels_search.date_error':
    'Oops, there seems to be something wrong with the chosen dates',
  'hotels_search.date_picker.select_date': 'Select date',
  'hotels_search.filter.free_cancellation': 'Free cancellation',
  'hotels_search.filter.hotel_facilities_filter.airport_shuttle':
    'Airport shuttle',
  'hotels_search.filter.hotel_facilities_filter.family_rooms': 'Family rooms',
  'hotels_search.filter.hotel_facilities_filter.facilities_for_disabled':
    'Facilities for Disabled Guests',
  'hotels_search.filter.hotel_facilities_filter.fitness_center':
    'Fitness Center',
  'hotels_search.filter.hotel_facilities_filter.parking': 'Parking',
  'hotels_search.filter.hotel_facilities_filter.free_parking': 'Free Parking',
  'hotels_search.filter.hotel_facilities_filter.valet_parking': 'Valet Parking',
  'hotels_search.filter.hotel_facilities_filter.indoor_pool': 'Indoor Pool',
  'hotels_search.filter.hotel_facilities_filter.pets_allowed': 'Pets allowed',
  'hotels_search.filter.hotel_facilities_filter.spa': 'Spa',
  'hotels_search.filter.hotel_facilities_filter.title': 'Amenities',
  'hotels_search.filter.hotel_facilities_filter.wifi': 'Wi-Fi',
  'hotels_search.filter.hotel_facilities_popup.save': 'Save',
  'hotels_search.filter.hotel_facilities_popup.title': 'Hotel facilities',
  'hotels_search.filter.price_filter.price': 'Price',
  'hotels_search.filter.price_popup.save': 'Save',
  'hotels_search.filter.price_popup.title': 'Price range',
  'hotels_search.filter.price_popup.subtitle': 'per stay',
  'hotels_search.filter.score_filter.rating': 'Rating',
  'hotels_search.filter.score_filter.rating.6': 'pleasant 6+',
  'hotels_search.filter.score_filter.rating.7': 'good 7+',
  'hotels_search.filter.score_filter.rating.8': 'very good 8+',
  'hotels_search.filter.score_filter.rating.9': 'superb 9+',
  'hotels_search.filter.score_filter.rating.any': 'any',
  'hotels_search.filter.score_popup.save': 'Save',
  'hotels_search.filter.stars_filter.stars': 'Stars',
  'hotels_search.filter.stars_filter.unrated': 'unrated',
  'hotels_search.filter.stars_popup.save': 'Save',
  'hotels_search.filter.stars_popup.title': 'Hotel stars',
  'hotels_search.filter.stars_popup.unrated': 'Unrated',
  'hotels_search.filter.order_by': 'Sort',
  'hotels_search.filter.order_filter.price': 'price',
  'hotels_search.filter.order_filter.distance': 'distance from center',
  'hotels_search.filter.order_filter.stars': 'stars',
  'hotels_search.filter.order_popup.price': 'Price',
  'hotels_search.filter.order_popup.distance': 'Distance from center',
  'hotels_search.filter.order_popup.title': 'Sort by',
  'hotels_search.filter.order_popup.stars': 'Stars',
  'hotels_search.load_more': 'Load more...',
  'hotels_search.header.to': 'to',
  'hotels_search.hotel_distance.in_city_center': 'In the city center',
  'hotels_search.hotel_distance.meters_from_center':
    '__distance__m from center',
  'hotels_search.hotel_distance.kilo_meters_from_center':
    '__distance__km from center',
  'hotels_search.all_hotels_search_list.show_map': 'Show map',
  'hotels_search.all_hotels_search_list.show_list': 'Show list',

  'single_hotel.bedding_info.guests': '__numberOfGuests__ Guests',
  'single_hotel.bedding_info.or': ' or ',
  'single_hotel.book_now': 'Book Now',
  'single_hotel.book_now.description':
    '__1_personCount__ Guests · __2_numberOfRooms__ Rooms',
  'single_hotel.book_now.alert_title': 'Not enough beds for everyone',
  'single_hotel.book_now.alert_body':
    'Your selection accommodates less than __numberOfGuests__ persons',
  'single_hotel.book_now.alert_ok': "Thats's fine",
  'single_hotel.description.facilities.show_less': 'Show less',
  'single_hotel.description.facilities.show_more': 'More',
  'single_hotel.hotel_detail_screen.hotel_not_found': 'Hotel not found.',
  'single_hotel.room_badges.breakfast_included': 'Breakfast included',
  'single_hotel.room_badges.free_cancellation': 'Free cancellation',
  'single_hotel.room_list.rooms': 'Rooms',
  'single_hotel.room_picker.select': 'Select',
  'single_hotel.powered_by': 'Powered by',
  'single_hotel.description.description': 'Description',
  'single_hotel.description.equipment': 'Equipment',
  'single_hotel.description.show_more': 'Show More',
  'single_hotel.description.show_less': 'Show Less',
  'single_hotel.hotel_review.reviews': '__count__ Reviews',
  'single_hotel.hotel_review.rating.6': 'Pleasant',
  'single_hotel.hotel_review.rating.7': 'Good',
  'single_hotel.hotel_review.rating.8': 'Very good',
  'single_hotel.hotel_review.rating.9': 'Perfect',
  'single_hotel.room_summary.summary': 'Summary',
  'single_hotel.room_summary.total': 'Total',
  'single_hotel.increment_decrement.count': 'Count',
  'single_hotel.alert.cannot_book_more_rooms_than_guests':
    'You cannot book more rooms than there are guests.',
};

export default HotelsVocabulary;
