language: node_js
node_js: '8' # latest 8.x release

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add greenkeeper-lockfile@1

install: yarn install
before_script: greenkeeper-lockfile-update
script: ./app/scripts/test.sh
after_script: greenkeeper-lockfile-upload

cache: yarn

notifications:
  email:
    on_success: change
    on_failure: always
