language: node_js
node_js: 'node' # latest stable Node.js release

install:
  - yarn install

script:
  - ./app/scripts/test.sh

after_success:
  - chmod -x ./app/scripts/deploy.sh # make deploy script executable

deploy:
  skip_cleanup: true
  provider: script
  script: ./app/scripts/deploy.sh
  on:
    branch: master

cache: yarn

notifications:
  email:
    on_success: change
    on_failure: always
