language: node_js
node_js: '8' # latest 8.x release

before_install: yarn global add greenkeeper-lockfile@1
install: yarn install
before_script: greenkeeper-lockfile-update
script: ./app/scripts/test.sh
after_script: greenkeeper-lockfile-upload

#deploy:
#  provider: script
#  skip_cleanup: true
#  script: chmod +x ./app/scripts/deploy.sh && ./app/scripts/deploy.sh
#  on:
#    branch: master

cache: yarn

notifications:
  email:
    on_success: change
    on_failure: always
