language: node_js
node_js: '8' # latest 8.x release

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install

# When one of the build commands returns a non-zero exit code, the Travis CI
# build runs the subsequent commands as well, and accumulates the build result.
script:
  - yarn test-ci
  - node scripts/expo

cache: yarn

notifications:
  email:
    on_success: change
    on_failure: always
