language: node_js
node_js: 'node' # latest stable Node.js release

install:
  - yarn install

script:
  - ./app/scripts/test.sh

cache: yarn

notifications:
  email:
    on_success: change
    on_failure: always
