# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/react-native-app

    steps:
      - checkout
      - attach_workspace:
           at: ~/react-native-app

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      # Run tests!
      - run: yarn test-ci
      - persist_to_workspace:
          root: .
          paths: .

  release:
    macos:
      xcode: 9.2.0

    working_directory: ~/react-native-app

    steps:
      - attach_workspace:
           at: ~/react-native-app
      - run: yarn release

workflows:
  version: 2
  build-and-release:
    jobs:
      - build
      - release:
          requires:
           - build
          filters:
            branches:
              only:
                - circle-ci-release-ios