// @flow

export type PicturesArray = Array<{
  lowRes: string,
  highRes: string,
  isMain: boolean,
}>;

export type Address = {
  streetLine: string,
  city: string,
  coordinates: {
    lat: number,
    lng: number,
  },
};

// Once we have GraphQL, we can delete this and use the type generated by Relay Compiler
export type Hotel = {
  id: string,
  name: string,
  stars: 1 | 2 | 3 | 4 | 5,
  rating: {
    score: number,
    description: string,
  },
  address: Address,
  photoUrl: string,
  pictures: PicturesArray,
  description: string,
  facilities: {
    edges: Array<{
      node: {
        name: string,
      },
    }>,
  },
  rooms: {
    edges: Array<{
      node: {
        id: string,
        type: string,
        maxPersons: number,
        bedding: ?Array<{
          type: string,
          amount: number,
        }>,
      },
    }>,
  },
};

const hotel: Hotel = {
  id: 'aG90ZWw6MjM5MTU1',
  name: 'Siam Kempinski Hotel Bangkok',
  stars: 5,
  rating: {
    score: 9.1,
    description: 'Superb',
  },
  address: {
    streetLine: '991/9 Rama I Road',
    city: 'Bangkok',
    coordinates: {
      lat: 13.748429,
      lng: 100.53479,
    },
  },
  photoUrl: 'http://aff.bstatic.com/images/hotel/max500/109/109604100.jpg',
  pictures: [
    {
      lowRes: 'http://aff.bstatic.com/images/hotel/max500/109/109604100.jpg',
      highRes: 'http://aff.bstatic.com/images/hotel/max500/109/109604100.jpg',
      isMain: true,
    },
    {
      lowRes: 'http://aff.bstatic.com/images/hotel/max500/588/58853664.jpg',
      highRes: 'http://aff.bstatic.com/images/hotel/max500/588/58853664.jpg',
      isMain: false,
    },
    {
      lowRes: 'http://aff.bstatic.com/images/hotel/max500/588/58853664.jpg',
      highRes: 'http://aff.bstatic.com/images/hotel/max500/588/58853664.jpg',
      isMain: false,
    },
    {
      lowRes: 'http://aff.bstatic.com/images/hotel/max500/588/58853664.jpg',
      highRes: 'http://aff.bstatic.com/images/hotel/max500/588/58853664.jpg',
      isMain: false,
    },
    {
      lowRes: 'http://aff.bstatic.com/images/hotel/max500/588/58853664.jpg',
      highRes: 'http://aff.bstatic.com/images/hotel/max500/588/58853664.jpg',
      isMain: false,
    },
  ],
  description:
    "Luxurious stays await at Siam Kempinski Hotel Bangkok, with multiple pools situated within landscaped grounds. Steps from Siam Paragon shopping centre, it features free WiFi, fine dining and a world-class spa.\n\nSiam Kempinski Hotel Bangkok enjoys easy access to Siam BTS Skytrain Station through Siam Paragon Mall. Suvarnabhumi International Airport is about 24 km from the hotel.\n\nThe spacious rooms at Siam Kempinski Hotel Bangkok are contemporary and stylish. Each features tea/coffee making facilities with an electric kettle and a flat-screen TV with international channels. Complimentary soft drinks and local beer are available from the minibar. En suite bathrooms have slippers, free toiletries and a bath or shower.\n\nSiam Kempinski boasts 3 restaurants offering an international buffet breakfast, modern Thai cuisine and and all-day dining.\n\nPathumwan is a great choice for travellers interested in shopping for clothes, shopping and food.\n\nThis is our guests' favourite part of Bangkok, according to independent reviews.\n\nThis property also has one of the best-rated locations in Bangkok! Guests are happier about it compared to other properties in the area.\n\nSolo travellers particularly like the location — they rated it 9.5 for a one-person stay.\n\nThis property is also rated for the best value in Bangkok! Guests are getting more for their money when compared to other properties in this city.\n\nWe speak your language!\n\nHotel Chain : Kempinski",
  facilities: {
    edges: [
      {
        node: {
          name: 'Restaurant',
        },
      },
      {
        node: {
          name: 'Room service',
        },
      },
      {
        node: {
          name: 'Meeting/banquet facilities',
        },
      },
      {
        node: {
          name: 'Bar',
        },
      },
      {
        node: {
          name: '24-hour front desk',
        },
      },
      {
        node: {
          name: 'Sauna',
        },
      },
      {
        node: {
          name: 'Fitness centre',
        },
      },
      {
        node: {
          name: 'Newspapers',
        },
      },
      {
        node: {
          name: 'Garden',
        },
      },
      {
        node: {
          name: 'Terrace',
        },
      },
      {
        node: {
          name: 'Non-smoking rooms',
        },
      },
      {
        node: {
          name: 'Airport shuttle',
        },
      },
      {
        node: {
          name: 'Business centre',
        },
      },
      {
        node: {
          name: 'Babysitting/child services',
        },
      },
      {
        node: {
          name: 'Laundry',
        },
      },
      {
        node: {
          name: 'Dry cleaning',
        },
      },
      {
        node: {
          name: 'Facilities for disabled guests',
        },
      },
      {
        node: {
          name: 'Family rooms',
        },
      },
      {
        node: {
          name: 'VIP room facilities',
        },
      },
      {
        node: {
          name: 'Ironing service',
        },
      },
      {
        node: {
          name: 'Bridal suite',
        },
      },
      {
        node: {
          name: 'Lift',
        },
      },
      {
        node: {
          name: 'Safety deposit box',
        },
      },
      {
        node: {
          name: 'Currency exchange',
        },
      },
      {
        node: {
          name: 'Spa and wellness centre',
        },
      },
      {
        node: {
          name: 'Massage',
        },
      },
      {
        node: {
          name: 'Gift shop',
        },
      },
      {
        node: {
          name: 'Shoeshine',
        },
      },
      {
        node: {
          name: 'Car hire',
        },
      },
      {
        node: {
          name: 'Fax/photocopying',
        },
      },
      {
        node: {
          name: 'Luggage storage',
        },
      },
      {
        node: {
          name: 'Shops (on site)',
        },
      },
      {
        node: {
          name: 'Air conditioning',
        },
      },
      {
        node: {
          name: 'ATM/cash machine on site',
        },
      },
      {
        node: {
          name: 'Restaurant (à la carte)',
        },
      },
      {
        node: {
          name: 'Restaurant (buffet)',
        },
      },
      {
        node: {
          name: 'Snack bar',
        },
      },
      {
        node: {
          name: 'Sun terrace',
        },
      },
      {
        node: {
          name: 'Outdoor pool (all year)',
        },
      },
      {
        node: {
          name: 'Concierge service',
        },
      },
      {
        node: {
          name: 'Trouser press',
        },
      },
      {
        node: {
          name: "Kids' club",
        },
      },
      {
        node: {
          name: 'Daily maid service',
        },
      },
      {
        node: {
          name: 'WiFi available in all areas',
        },
      },
      {
        node: {
          name: 'Parking garage',
        },
      },
      {
        node: {
          name: 'Salt-water pool',
        },
      },
      {
        node: {
          name: 'Pool/beach towels',
        },
      },
      {
        node: {
          name: 'Pool bar',
        },
      },
      {
        node: {
          name: 'Wine/champagne',
        },
      },
      {
        node: {
          name: 'Tickets to attractions or shows',
        },
      },
      {
        node: {
          name: 'Airport pick up',
        },
      },
      {
        node: {
          name: 'Airport drop off',
        },
      },
      {
        node: {
          name: 'On-site coffee house',
        },
      },
      {
        node: {
          name: 'Beauty Services',
        },
      },
      {
        node: {
          name: 'Facial treatments',
        },
      },
      {
        node: {
          name: 'Body Treatments',
        },
      },
      {
        node: {
          name: 'Body scrub',
        },
      },
      {
        node: {
          name: 'Spa Facilities',
        },
      },
      {
        node: {
          name: 'Spa lounge/relaxation area',
        },
      },
      {
        node: {
          name: 'Spa/wellness packages',
        },
      },
      {
        node: {
          name: 'Fitness',
        },
      },
      {
        node: {
          name: 'Fitness/spa locker rooms',
        },
      },
      {
        node: {
          name: 'Swimming pool',
        },
      },
    ],
  },
  rooms: {
    edges: [
      {
        node: {
          id: 'aG90ZWxSb29tOjIzOTE1NTAx',
          type: 'Twin/Double',
          maxPersons: 2,
          bedding: [
            {
              type: 'Single bed(s)',
              amount: 2,
            },
            {
              type: 'Large bed(s) (King size)',
              amount: 1,
            },
          ],
        },
      },
      {
        node: {
          id: 'aG90ZWxSb29tOjIzOTE1NTAy',
          type: 'Twin/Double',
          maxPersons: 2,
          bedding: [
            {
              type: 'Single bed(s)',
              amount: 2,
            },
            {
              type: 'Large bed(s) (King size)',
              amount: 1,
            },
          ],
        },
      },
      {
        node: {
          id: 'aG90ZWxSb29tOjIzOTE1NTAz',
          type: 'Suite',
          maxPersons: 2,
          bedding: null,
        },
      },
      {
        node: {
          id: 'aG90ZWxSb29tOjIzOTE1NTA0',
          type: 'Twin/Double',
          maxPersons: 2,
          bedding: [
            {
              type: 'Single bed(s)',
              amount: 2,
            },
            {
              type: 'Large bed(s) (King size)',
              amount: 1,
            },
          ],
        },
      },
      {
        node: {
          id: 'aG90ZWxSb29tOjIzOTE1NTA1',
          type: 'Double',
          maxPersons: 2,
          bedding: [
            {
              type: 'Large bed(s) (King size)',
              amount: 1,
            },
          ],
        },
      },
      {
        node: {
          id: 'aG90ZWxSb29tOjIzOTE1NTA2',
          type: 'Suite',
          maxPersons: 4,
          bedding: null,
        },
      },
      {
        node: {
          id: 'aG90ZWxSb29tOjIzOTE1NTA4',
          type: 'Suite',
          maxPersons: 2,
          bedding: null,
        },
      },
      {
        node: {
          id: 'aG90ZWxSb29tOjIzOTE1NTEz',
          type: 'Twin/Double',
          maxPersons: 2,
          bedding: [
            {
              type: 'Single bed(s)',
              amount: 2,
            },
            {
              type: 'Large bed(s) (King size)',
              amount: 1,
            },
          ],
        },
      },
      {
        node: {
          id: 'aG90ZWxSb29tOjIzOTE1NTE0',
          type: 'Suite',
          maxPersons: 2,
          bedding: null,
        },
      },
      {
        node: {
          id: 'aG90ZWxSb29tOjIzOTE1NTE1',
          type: 'Suite',
          maxPersons: 4,
          bedding: null,
        },
      },
      {
        node: {
          id: 'aG90ZWxSb29tOjIzOTE1NTIy',
          type: 'Twin/Double',
          maxPersons: 2,
          bedding: [
            {
              type: 'Single bed(s)',
              amount: 2,
            },
            {
              type: 'Extra-large double bed(s) (Super-king size)',
              amount: 1,
            },
          ],
        },
      },
      {
        node: {
          id: 'aG90ZWxSb29tOjIzOTE1NTIz',
          type: 'Suite',
          maxPersons: 2,
          bedding: [
            {
              type: 'Extra-large double bed(s) (Super-king size)',
              amount: 1,
            },
          ],
        },
      },
      {
        node: {
          id: 'aG90ZWxSb29tOjIzOTE1NTI0',
          type: 'Suite',
          maxPersons: 2,
          bedding: null,
        },
      },
    ],
  },
};

export default hotel;
