# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

workspace 'reactNativeApp.xcworkspace'

def react_native_pods()
  pod 'React', path: '../node_modules/react-native', subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'CxxBridge',
    'DevSupport',
  ]

  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga/yoga.podspec'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'
  pod 'RNGestureHandler', path: '../node_modules/react-native-gesture-handler'
end

def hotels_package_modules()
  pod 'react-native-maps', path: '../node_modules/react-native-maps'
  pod 'react-native-async-storage', :path => '../node_modules/@react-native-community/async-storage'
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
end

def react_native_modules()
  pod 'RNModules', path: './RNModules', subspecs: [
    'RNLogging',
    'RNTranslationManager',
    'RNCurrencyManager',
    'RNDeviceInfo',
    'RNAppleWallet',
    'RNCardManager'
  ]
end

target 'reactNativeApp' do
  react_native_pods()
  react_native_modules()
  hotels_package_modules()
end

target 'RNKiwiMobile' do
  react_native_pods()
  react_native_modules()
  hotels_package_modules()
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
  end

  # This step is necessary to make it possible
  # to use other configurations than Debug or Release
  installer.pods_project.build_configurations.each do |config|
    if config.name == 'Staging'
        config.build_settings['CONFIGURATION_BUILD_DIR'] = '$(BUILD_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)'
    end
  end
end
