# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

workspace 'reactNativeApp.xcworkspace'

def react_native_pods() 
  pod 'React', path: '../node_modules/react-native', subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'CxxBridge',
    'DevSupport',
  ]

  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga/yoga.podspec'
  pod 'react-native-maps', path: '../node_modules/react-native-maps'
  
  pod 'RNLogging', :path => '../node_modules/@kiwicom/react-native-native-modules'
  pod 'RNTranslationManager', :path => '../node_modules/@kiwicom/react-native-native-modules'
  pod 'RNColors', :path => '../node_modules/@kiwicom/react-native-native-modules'
  pod 'RNCurrencyManager', :path => '../node_modules/@kiwicom/react-native-native-modules'
  pod 'RNDeviceInfo', :path => '../node_modules/@kiwicom/react-native-native-modules'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'
  pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'

end 

target 'RNPlayground' do
  react_native_pods()
end

target 'RNKiwiMobile' do
  react_native_pods()

  pod 'RNNavigator', :path => '../node_modules/@kiwicom/react-native-native-modules'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
  end

end
