# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

workspace 'reactNativeApp.xcworkspace'

def react_native_pods() 
  pod 'React', path: '../node_modules/react-native', subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'CxxBridge',
    'DevSupport',
  ]

  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga/yoga.podspec'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
end

def common_modules()
  pod 'react-native-maps', path: '../node_modules/react-native-maps'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
end

def mmb_package_modules()
  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
  pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'
  pod 'RNReverseGeocode', :path => '../node_modules/@kiwicom/react-native-reverse-geocode'
  pod 'RNShare', :path => '../node_modules/react-native-share'
end

def react_native_modules()
  pod 'RNModules', path: './RNModules', subspecs: [
    'RNLogging',
    'RNTranslationManager',
    'RNCurrencyManager',
    'RNDeviceInfo',
    'RNAppleWallet',
    'RNCardManager'
  ]
end

target 'reactNativeApp' do
  react_native_pods()
  react_native_modules()
  common_modules()
  mmb_package_modules()
end

target 'RNKiwiMobile' do
  react_native_pods()
  react_native_modules()
  common_modules()
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
  end
end
