# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  private_lane :build_deploy do |options|

    get_certificates(
      username: ENV["APPLE_ID"]
    )

    get_provisioning_profile(
      username: ENV["APPLE_ID"],
      app_identifier: options[:app_id]
    )

    build_ios_app(
      scheme: options[:scheme],
      workspace: "reactNativeApp.xcworkspace",
      include_bitcode: true
    )

    increment_build_number

    upload_to_testflight(
      username: ENV["APPLE_ID"],
      skip_waiting_for_build_processing: true,
    )
  end

  desc "Build and deploy reactNativeApp to TestFlight"
  lane :beta do
    build_deploy(
      app_id: "com.kiwi.reactNative",
      scheme: "reactNativeApp"
    )
  end

  desc "Build and deploy RNNativePlayground to TestFlight"
  lane :staging do
    build_deploy(
      app_id: "com.kiwi.mobile.rniosplayground",
      scheme: "RNNativePlayground - Staging"
    )
  end

end
