// @flow

import '../../shared/src/popup/__tests__/ButtonPopupPlayground.test.js';
import '../../shared/src/forms/datePicker/__tests__/DatePicker.test.js';
import '../../shared/src/forms/__tests__/Slider.test.js';
import '../../shared/src/cards/__tests__/SimpleCard.test.js';
import '../../shared/src/buttons/__tests__/IncrementDecrementButtons.test.js';
import '../../shared/src/buttons/__tests__/Button.test.js';
import '../../shared/src/badge/__tests__/AdaptableBadge.test.js';
import '../../shared/src/__tests__/Text.test.js';
import '../../shared/src/__tests__/ReadMore.test.js';
import '../../hotels/src/singleHotel/roomPicker/__tests__/RoomPicker.test.js';
import '../../hotels/src/singleHotel/roomList/__tests__/RoomDescription.test.js';
import '../../hotels/src/singleHotel/roomList/__tests__/RoomBadges.test.js';
import '../../hotels/src/singleHotel/bookNow/__tests__/BookNow.test.js';
import '../../hotels/src/gallery/__tests__/PhotosStripeHeader.test.js';
import '../../hotels/src/filter/stars/__tests__/StarsPopup.test.js';
import '../../hotels/src/filter/stars/__tests__/StarsFilter.test.js';
import '../../hotels/src/allHotels/searchForm/locationPicker/__tests__/SuggestionList.test.js';
import '../../hotels/src/allHotels/searchForm/locationPicker/__tests__/RecentSearches.test.js';
import '../../hotels/src/allHotels/__tests__/LoadMoreButton.test.js';
import '../../MMB/src/list/__tests__/CityImage.test.js';
