// @flow
import hotel from '../fakeHotel';
import withFakeData from '../withFakeData';

import type { Address } from '../fakeHotel';
import Location from './Location';

// This will be replaced with type generated by Relay compiler
export type LocationContainer_address = Address;

export default withFakeData(Location, () => ({
  address: hotel.address,
}));
