platform :ios, '9.0'

rn_path = '../../node_modules/react-native'

target 'RNAccountManager' do
  project 'RNAccountManager.xcodeproj'
  
  pod 'React', path: rn_path, subspecs: [
    'Core',
  ]
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"

end


